name: siklero
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.2.8
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.5
  google_maps_flutter: ^2.2.0
  sliding_up_panel: ^2.0.0+1
  connectivity_plus: ^3.0.2
  email_validator: ^2.1.17
  intl: ^0.17.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  url_launcher: ^6.1.6
  internet_connection_checker: ^1.0.0+1
  permission_handler: ^10.2.0
  expandable: ^5.0.1
  http: ^0.13.5
  flutter_pw_validator: ^1.4.2
  youtube_player_flutter: ^8.1.1
  image_picker: ^0.8.6
  firebase_storage: ^11.0.6
  photo_view: ^0.14.0
  flutter_google_places: ^0.3.0
  google_api_headers: ^1.5.0
  to_csv: ^1.1.1

flutter_native_splash:
  color: "#ed8f5b"
  image: asset/img/siklero-logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/img/
    - asset/img/tools_image/
    - asset/img/hotlines_image/
    - asset/img/preparation_image/
    - asset/img/repair_image/
    - asset/img/avoiding-crashes_image/
    - asset/img/first-aid_image/
    - asset/locations.json

  fonts:
    - family: OpenSans
      fonts:
        - asset: asset/font/OpenSans-Regular.ttf
          weight: 400
        - asset: asset\font\OpenSans-Bold.ttf
          weight: 700
    - family: OpenSansCondensed
      fonts:
        - asset: asset/font/OpenSans_Condensed-Regular.ttf